export {default as BigText} from './BigText'
export {default as Hero} from './Hero'
export {default as PageHeader} from './PageHeader'
export {default as Quote} from './Quote'
export {default as MiradorGallery} from './MiradorGallery'
export {default as SectionText} from './SectionText'
export {default as Social} from './Social'
export {default as TwoColumn} from './TwoColumn'
